const {
  CONTRACT,
  PRICING_TERM,
  TARGET_TERM,
  TARGET_LEVEL,
  TARGET_TERM_LOOKUP,
  DISCOUNT,
  NOTE,
  CONTRACT_LOOKUP,
  DISCOUNT_LOOKUP,
  PRICING_TERM_LOOKUP,
  NORMALIZATION,
  NORMALIZATION_MARKET,
  RULE_LOOKUP
} = require('./contract');
const { DATA_SET } = require('./dataSet');
const { PROCESS } = require('./process');
const { PROJECT, PROJECT_LOOKUP } = require('./project');
const {
  AIR_APPLICATION_ID,
  ADVITO_CLIENT,
  ADVITO_GEOSET_ID
} = require('./client');
const { LIBRARY_LOOKUP, LOCATION_LOOKUP } = require('./library');
const {
  LOCATION_COLLECTION,
  TRAVEL_SECTOR_COLLECTION,
  AIRLINE_GROUP_COLLECTION,
  PREFERRED_AIRLINE_COLLECTION,
  PREFERRED_AIRLINE_LOOKUP
} = require('./collection');

module.exports = {
  AIR_APPLICATION_ID,
  ADVITO_CLIENT,
  ADVITO_GEOSET_ID,
  CONTRACT,
  PRICING_TERM,
  TARGET_TERM,
  TARGET_LEVEL,
  TARGET_TERM_LOOKUP,
  DISCOUNT,
  NORMALIZATION,
  NORMALIZATION_MARKET,
  NOTE,
  CONTRACT_LOOKUP,
  DISCOUNT_LOOKUP,
  PRICING_TERM_LOOKUP,
  RULE_LOOKUP,
  DATA_SET,
  PROCESS,
  PROJECT,
  LIBRARY_LOOKUP,
  LOCATION_LOOKUP,
  PROJECT_LOOKUP,
  LOCATION_COLLECTION,
  TRAVEL_SECTOR_COLLECTION,
  AIRLINE_GROUP_COLLECTION,
  PREFERRED_AIRLINE_COLLECTION,
  PREFERRED_AIRLINE_LOOKUP
};
