export const PROJECT = `id
        clientId
        clientName
        name
        description
        isDeleted
        projectTypeId
        projectTypeName
        savingsTypeId
        savingsTypeName
        effectiveFrom
        effectiveTo
        reportFrom
        reportTo
        projectManagerId
        projectManagerName
        projectManagerEmail
        leadAnalystId
        leadAnalystName
        leadAnalystEmail
        dataSpecialistId
        dataSpecialistName
        dataSpecialistEmail
        currencyId
        currencyName
        distanceUnitId
        distanceUnitName
        progress
        favorite`;
