export const SCENARIO = `scenarioId
        projectId
        shortName
        name
        description
        airlineContracts
        contractTargets
        preferredAirlines
        useHistoricalShare
        tripDistribution
        effectiveSavings
        influenceLevelCd
        priceInfluenceLevelCd
        biasOverride
        servedMarketThreshold
        overlapThreshold
        segmentIncrease
        fareIncrease
        useHistoricalFares
        ignoresSmallQsi
        smallQsiThreshold`;
